### ISSUE TITLE
[html] 2.5.1 別仕様へのリンク切れ

### ISSUE THREAD

**Issue by SaekiTominaga** [momdo/momdo.github.io#108]
https://momdo.github.io/html/urls-and-fetching.html#valid-non-empty-url
「妥当なURL文字列」のリンクURLが間違っているので、修正をお願いします。（2か所）

```diff
-https://triple-underscore.github.io/U#valid-url-string
+https://triple-underscore.github.io/URL-ja.html#valid-url-string

**Comment by momdo** [comment]
@SaekiTominaga 
ご指摘ありがとうございます。
修正しましたので確認ください。
