### ISSUE TITLE
[css-values-3] 4.3.1. 互換性のある単位の見直し

### ISSUE THREAD

**Issue by momdo** [momdo/momdo.github.io#109]
https://twitter.com/woopsdez/status/1102811446587490305 より

https://www.w3.org/TR/2019/CR-css-values-3-20190131/#compat
> Each group of compatible units defines which among them is the canonical unit that will be used for serialization.

https://momdo.github.io/css3-values/#compat
> 互換性のある単位の各グループは、単位間がシリアル化のために使用される規準的な単位であるものを定義する。

各グループが「どこから出てきた？」というコメント。

**Comment by makotom** [comment]
訳文を精読すると,

1) "互換性のある単位" はいくつかの単位の集合でありそのような集合が複数あること
2) "互換性のある単位の各グループ" がそれらの単位の集合について言及していること

は読解可能であるので, 何かが間違っているとは思いません.

// なお原文において上記は, "compatible unit<em>s</em> ... _those (= units)_ related by ... <em>or</em> ..." や "each group of _compatible units_" などとの表記から自明みが特に強い.

もっとも, 上記のような論理構造を明快に示す和文は存在しうるかもしれないので, 参考案を挙げてみることにします. (訳出の方針等もあると思うので, よしなに参考にしていただけると幸いです. 変わっているところを太字にしています.)

> 互換性のある単位 (px と in 間<strong>における</strong> 96:1 の係数<strong>や</strong>, em と px 間<strong>において</strong>計算され<strong>る</strong> font-size 係数のような, 静的な倍数因子によって<strong>関連付けられる複数の単位</strong>) は, 単一の規準的な単位に変換される. 互換性のある単位の各<strong>組</strong>は, <strong>それらの間における規準的な単位を定義し, シリアル化の際に使用する</strong>.

**Comment by momdo** [comment]
@makotom 
コメントありがとうございます…！（確かに自明みが強いですよねえ…）

**Comment by momdo** [comment]
特に良化できる見込みがないのでClose
