### ISSUE TITLE
[wai-aria-1.2] regionの訳について

### ISSUE THREAD

**Issue by azusa-tomita** [momdo/momdo.github.io#110]
https://momdo.github.io/wai-aria-1.2/#region
> に関連して、ユーザーが容易にセクションに移動したく、かつページの要約に記載されるセクションを持つのに適当である、具体的で、著者指定の目的に沿う、十分重要なコンテンツを含む知覚可能なsection。

https://www.w3.org/TR/2018/WD-wai-aria-1.2-20181218/#region
> A perceivable section containing content that is relevant to a specific, author-specified purpose and sufficiently important that users will likely want to be able to navigate to the section easily and to have it listed in a summary of the page. 

`relevant to a specific, author-specified purpose`に該当する日本語訳の先頭部分が欠落しているようです。

**Comment by momdo** [comment]
@azusa-tomita 翻訳を修正してみましたので、確認ください。

**Comment by azusa-tomita** [comment]
👍 
迅速な対応ありがとうございます
