### ISSUE TITLE
[wai-aria-1.2] aria-live 値「assertive」の説明で「る」が抜けている

### ISSUE THREAD

**Issue by yamanoku** [momdo/momdo.github.io#111]
https://momdo.github.io/wai-aria-1.2/#aria-live

assertiveの値にて
> 領域への更新が最高の優先順位を持ち、すぐにユーザーに提示「されべき」であることを示す。

「る」が抜けてるようです

**Comment by yamanoku** [comment]
1.1もでした
https://momdo.github.io/wai-aria-1.1/#aria-live

**Comment by momdo** [comment]
ありがとうございます。修正しました。
