### ISSUE TITLE
[html]誤記３箇所「4.6.6.24 その他のリンクタイプ」「4.9.8 tr要素」「4.10.5.1.17 File Upload状態（type=file）」

### ISSUE THREAD

**Issue by mtrootyy** [momdo/momdo.github.io#112]
HTML Living Standardの日本語訳は、大変参考にさせていただいております。
　誤記箇所をいくつか見つけたので、お知らせします。

一　「4.6.6.24 その他のリンクタイプ」の誤記箇所
https://momdo.github.io/html/links.html#other-link-types
誤：適合性チェッカーは、値が許容されるかどうかを確立するためにmicroformats wikiのexisting-rel-valuesページで指定される情報を使用**してもよい**
正：適合性チェッカーは、値が許容されるかどうかを確立するためにmicroformats wikiのexisting-rel-valuesページで指定される情報を使用**しなければならない**

参考
https://html.spec.whatwg.org/multipage/links.html#other-link-types
> Conformance checkers **must** use the information given on the microformats wiki existing-rel-values page to establish if a value is allowed or not

　

二　「4.9.8 tr要素」の誤記箇所
https://momdo.github.io/html/tables.html#the-tr-element
誤：tr要素は、テーブルでセルの**列**を表す。
正：tr要素は、テーブルでセルの**行**を表す。

　

三　「4.10.5.1.17 File Upload状態（type=file）」の誤記箇所
https://momdo.github.io/html/input.html#file-upload-state-(type=file)
> Bookkeeping details
> - ......
> - ......
> - ......
> - 以下のコンテンツ属性を指定してはならず、要素に適用しない：**accept**、alt、autocomplete、......
> - ......
> - ......

　↓

誤：以下のコンテンツ属性を指定してはならず、要素に適用しない：**accept**、alt、autocomplete、......
正：以下のコンテンツ属性を指定してはならず、要素に適用しない：alt、autocomplete、......

input要素のtype=fileには、accept属性は指定可能。

**Comment by momdo** [comment]
ありがとうございます。
指摘いただいた箇所は修正できているはずです。ご確認いただければと。

**Comment by mtrootyy** [comment]
確認しました。
ありがとうございました。
