### ISSUE TITLE
[html] 4.10.15 fieldset要素のコンテンツモデルの訳

### ISSUE THREAD

**Issue by SaekiTominaga** [momdo/momdo.github.io#113]
[fieldset要素](https://momdo.github.io/html/form-elements.html#the-fieldset-element)のコンテンツモデルの部分で

> フローコンテンツの後に続く、任意でlegend要素。

とありますが、これだと
```
<fieldset>
text
<legend>legend</legend>
</fieldset>
```
が正当なものであるように受け取れてしまうと思います。

[原文](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element)は以下なので、「任意でlegend要素と、それに続くフローコンテンツ。」あたりが適切でしょうか。

> Optionally a legend element, followed by flow content.

**Comment by momdo** [comment]
ありがとうございます。修正してみましたのでご確認ください。
