### ISSUE TITLE
"ハイパーリンク、またはbutton要素を作成するa要素"

### ISSUE THREAD

**Issue by yuko-m** [momdo/momdo.github.io#115]
https://momdo.github.io/html/images.html#a-link-or-button-containing-nothing-but-the-image:hyperlink

> ハイパーリンク、またはbutton要素を作成するa要素

「ハイパーリンクを作成するa要素、またはbutton要素」でどうでしょうか

**Comment by momdo** [comment]
@yuko-m issueありがとうございます。

> ハイパーリンクをを作成するa要素、またはbutton要素が、テキストコンテンツを持たないが1つ以上の画像を含む場合、alt属性はリンクまたはボタンの目的を併せて伝えるテキストを含まなければならない。

としました。

**Comment by yuko-m** [comment]
@momdo とても読みやすくなりました。ありがとうございます！
ただ、ハイパーリンクの後の **を** が重複してしまっているようです。

**Comment by momdo** [comment]
＠yuko-m （その後こっそり直しました）
