### ISSUE TITLE
[html] 4.9.11 tdとth要素の共通属性の訳

### ISSUE THREAD

**Issue by SaekiTominaga** [momdo/momdo.github.io#117]
[td / th 要素の colspan / rowspan の訳](https://momdo.github.io/html/tables.html#attr-tdth-colspan)が日本語的に分かりにくいので、以下のように変更するのはどうでしょうか。
とくに rowspan 属性に関しては、「値が0より大きく」の部分が誤訳となってしまっています。
なお、リンクアンカーになっている「妥当な負でないの整数」も日本語として不自然な気がしますが、これは他の部分にも影響するので（colgroup / col 要素の span 属性とか）、そのままにしています。

```diff
-tdおよびth要素は、値が0より大きくかつ1000以下の妥当な負でないの整数を指定しなければならない、colspanコンテンツ属性を持ってもよい。
+tdおよびth要素には、colspanコンテンツ属性を指定することができる。その値は0より大きく1000以下の妥当な負でないの整数でなければならない。
```

```diff
-tdおよびth要素はまた、値が0より大きくかつ65534以下の妥当な負でないの整数を指定しなければならない、rowspanコンテンツ属性を持ってもよい。この属性のために、値0は、セルが行グループですべての残りの行にまたがることを意味する。
+tdおよびth要素には、rowspanコンテンツ属性を指定することもできる。その値は65534以下の妥当な負でないの整数でなければならない。この属性の値が0の時、セルが行グループで残りのすべての行にまたがることを意味する。
```

**Comment by momdo** [comment]
@SaekiTominaga 
コメントありがとうございます。つい最近自分でも読んでて誤訳と言うことに気づいていました…（と言いつつ、なにもしていなかったわけですが）。

https://github.com/momdo/momdo.github.io/commit/d99df1b1dff51a7e745e48c035ccc6fef7d78c39 で修正しましたので確認ください。

**Comment by SaekiTominaga** [comment]
@momdo 
ご対応ありがとうございます。
割と最近まで Chrome が rowspan=0 を認識しないバグがあったのですが、いつの間にか対応されたようで、その関連で誤訳に気付いた次第です。
