### ISSUE TITLE
[wai-aria-1.1] presentationロール 「一部の要素はただ単に完結する」

### ISSUE THREAD

**Issue by bakera** [momdo/momdo.github.io#119]
以下の箇所は誤訳気味かもしれません。

>Some elements are only complete when additional descendant elements are provided. 
>追加の子孫要素が与えられる場合、一部の要素はただ単に完結する。

→一部の要素は、追加の子孫要素が与えられた場合にのみ完結する。
別案: 一部の要素は、追加の子孫要素が与えられてはじめて完成する。

**Comment by momdo** [comment]
@bakera 
遅くなりましたが、修正しましたのでご確認くださいませ。
