### ISSUE TITLE
[wai-aria-1.1] Presentational Roles Conflict Resolution 「適用のみされる」

### ISSUE THREAD

**Issue by bakera** [momdo/momdo.github.io#120]
これは誤訳かもしれません。

>aria-level is not a global attribute and would therefore only apply if the element was not in a presentational state.
>要素がプレゼンテーションステートではなかった場合、aria-levelはグローバル属性ではなく、したがって適用のみされる。

→aria-levelはグローバル属性ではなく、したがって、要素がプレゼンテーションステートでなかった場合のみ適用される。

**Comment by momdo** [comment]
@bakera 
遅くなりましたが、修正しましたのでご確認くださいませ。
