### ISSUE TITLE
[html] 4.10.5.3.10 placeholder属性とtitle属性の使い分けの解説文

### ISSUE THREAD

**Issue by SaekiTominaga** [momdo/momdo.github.io#122]
> For a longer hint or other advisory text, the title attribute is more appropriate.

> ヒントや他の助言テキストについては、title属性がより適切である。

"longer" が日本語訳では抜けてしまっています。
前の段落で "a short hint" として placeholder 属性を使うことができると書かれているように、ヒントの長さによってそれを placeholder 属性で表現するか、あるいは title 属性の方が適切であるかが変わってくるので、訳も「長いヒントや……」とした方がよさそうです。

**Comment by momdo** [comment]
@SaekiTominaga 
遅くなりましたが、修正しましたのでご確認くださいませ。
