### ISSUE TITLE
[accname-1.1]4.2内のテキストの欠落について

### ISSUE THREAD

**Issue by azusa-tomita** [momdo/momdo.github.io#123]
https://github.com/momdo/momdo.github.io/blob/master/accname-1.1/index.html#L865

この行の以下部分の2行目について、

```
もしくはネイティヴホスト言語のテキストによる代替要素（HTMLのラベルなど）である場合、
またはネイティヴホスト言語のテキストによる代替要素である場合：
```

原文の2行目にある `is a descendant of ` が脱落していました。

```
or is a native host language text alternative element (e.g. label in HTML), 
or is a descendant of a native host language text alternative element:
```

**Comment by momdo** [comment]
@azusa-tomita ありがとうございます。修正しましたのでご確認ください。（手違いでこのコミットではタイトルが変更されていますが）

**Comment by azusa-tomita** [comment]
👍 
確認にしました。ご対応ありがとうございます
