### ISSUE TITLE
パルパブルコンテンツの翻訳調整案

### ISSUE THREAD

**Issue by bakera** [momdo/momdo.github.io#125]
palpable contentの翻訳を見ていて、少しわかりにくいと思いましたので私見で訳を調整してみました。採用できそうなところがあるようでしたらご検討ください。
https://momdo.github.io/html/dom.html#palpable-content

以下調整案です。
(non-empty→「非空」も見直した方が良いかもしれませんが一旦そのままにしています。)

========

一般的な規則として、コンテンツモデルに任意のフローコンテンツまたはフレージングコンテンツを許可する要素は、その内容として、パルパブルコンテンツであり、かつhidden属性が指定されていないノードを少なくとも1つ持つべきである。

Note:
パルパブルコンテンツは、子孫として空でないテキストか、もしくはユーザーが聞く（audio要素）または見る（videoまたはimgまたはcanvas要素）または他の方法で相互作用する（たとえば、インタラクティブなフォームコントロール）ことのできる何らかのものを提供することによって、要素を非空にするものである。

この要件は厳しい要件ではないが、要素を合法的に空にできる多くのケースがあり、たとえば、スクリプトによって後で埋められるプレースホルダーとして使用される場合、または要素がテンプレートの一部であり、ほとんどのページでは埋められるが、一部のページで処理されない場合などがあげられる。

**Comment by momdo** [comment]
@bakera 

随分と長らくほったらかしにしてしまいましたが、コメントありがとうございます。
いただいた案をみながら修正しました。問題あるようでしたら、Reopenしていただければと思います。
