### ISSUE TITLE
[html-aria] 訳揺れ「任意のrole」「すべてのrole」

### ISSUE THREAD

**Issue by YusukeHirao** [momdo/momdo.github.io#127]
“Any role” に対しての訳で「任意のrole」「すべてのrole」と2つの訳揺れがあります。
https://momdo.github.io/html-aria/#dfn-any-role

どっちが適切が判断できなかったためPRでなくIssueなことご容赦ください。

**Comment by momdo** [comment]
@YusukeHirao 
コメントありがとうございます。「すべての」に統一しました。
