### ISSUE TITLE
[html] a要素のコンテンツモデルについて

### ISSUE THREAD

**Issue by yassh** [momdo/momdo.github.io#129]
> 透過的であるが、インタラクティブコンテンツの子孫、a要素の子孫、またはtabindex属性が指定された子孫が存在してはならない。

— https://momdo.github.io/html/text-level-semantics.html#the-a-element

と書かれていますが「a要素の内容にa要素の子要素が存在してはならないとはどういうことだ？」と混乱しました。

原文だとこうですね：

> Transparent, but there must be no interactive content descendant, a element descendant, or descendant with the tabindex attribute specified.

— https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

この文を読んで私は、a要素の内容にa要素**である**子孫が存在してはならないという意味だと解釈しました。もしその解釈が正しければ、誤解の生じないように、「透過的であるが、インタラクティブコンテンツである子孫、a要素である子孫、…」という表現に改めたほうがよいように思います。

**Comment by momdo** [comment]
@yassh 

コメントありがとうございます。

問題としている状況は、たとえば、次のようであってはいけないということですね。

```html
<!-- 仕様で禁止されている例 -->
<a href="hoge">
  <a href="fuga">pome</a>
</a>
```

これは、

- a要素は、a要素**の**子孫を含んではならない。
- a要素は、a要素**である**子孫が存在してはならない。

のように、どちらとでも日本語として表現できるでしょう。
結局のところ好みの問題でしょうから、翻訳を変更するまでの強い理由があるとは考えていませんが、いかがでしょうか。

**Comment by yassh** [comment]
HTMLが禁止しているのは、a要素の子孫として、a要素そのもの、もしくはインタラクティブコンテンツそのもの、もしくはtabindex属性が指定された要素そのものがあることだと思うのですが、違うでしょうか？

その理解が正しいのであれば、次のようなマークアップは不正になりますね。

```
<a href="hoge">
  <a href="fuga"></a>
  <input type="text">
</a>
```

しかし、

> 透過的であるが、インタラクティブコンテンツの子孫、a要素の子孫、またはtabindex属性が指定された子孫が存在してはならない。

という表現だと、「a要素の中にa要素はあるが、a要素の子孫はないからOK？」「a要素の中にインタラクティブコンテンツはあるが、インタラクティブコンテンツの子孫はないからOK?」という誤った認識が発生してしまう恐れがあると思います。

**Comment by momdo** [comment]
例示までの主張はそのとおりですが、

> 「a要素の中にa要素はあるが、a要素の子孫はないからOK？」（中略）という誤った認識が発生してしまう恐れ

"a要素の中にa要素はある"と言う場合に、その中のa要素が、（外の）a要素の子孫そのものであるので、そもそもの主張が矛盾しています。これは、

「a要素の中にa要素はあるが、a要素**である**子孫はないからOK？」

と言い換えても同じ理屈でしょうから、日本語訳に起因する問題になるとは考えていません。

**Comment by yassh** [comment]
> "a要素の中にa要素はある"と言う場合に、その中のa要素が、（外の）a要素の子孫そのものであるので、そもそもの主張が矛盾しています。これは、
> 
> 「a要素の中にa要素はあるが、a要素である子孫はないからOK？」
> 
> と言い換えても同じ理屈でしょうから、日本語訳に起因する問題になるとは考えていません。

よく考えたら、確かにそうですね。

それでは、「a要素の中にインタラクティブコンテンツはあるが、インタラクティブコンテンツの子孫はないからOK?」という誤った認識が発生してしまう恐れに関してはどうでしょうか？

**Comment by momdo** [comment]
> それでは、「a要素の中にインタラクティブコンテンツはあるが、インタラクティブコンテンツの子孫はないからOK?」という誤った認識が発生してしまう恐れに関してはどうでしょうか？

それは内側のa要素をインタラクティブコンテンツに読み替えればよいだけでは。

いずれにせよ、翻訳を変更する強い理由はないと判断しますのでこのissueはcloseします。
