### ISSUE TITLE
[html] 4.9.2 caption要素、4.9.3 colgroup要素の誤訳

### ISSUE THREAD

**Issue by SaekiTominaga** [momdo/momdo.github.io#130]
[4.9.2 caption要素](https://momdo.github.io/html/tables.html#the-caption-element) と [4.9.3 colgroup要素](https://momdo.github.io/html/tables.html#the-colgroup-element)のタグ省略に誤訳がありました。

> caption要素の直前がASCII空白文字またはコメントでない場合、caption要素の終了タグは省略することができる。

> colgroup要素の直前がASCII空白文字またはコメントでない場合、colgroup要素の終了タグは省略することができる。

「～～要素の直前」は正しくは「直後」です。

なお、原文はこうなっています。[4.9.2 The caption element](https://html.spec.whatwg.org/multipage/tables.html#the-caption-element), [4.9.3 The colgroup element](https://html.spec.whatwg.org/multipage/tables.html#the-colgroup-element)
> A caption element's end tag can be omitted if the caption element is not immediately followed by ASCII whitespace or a comment.

> A colgroup element's end tag can be omitted if the colgroup element is not immediately followed by ASCII whitespace or a comment.

**Comment by momdo** [comment]
@SaekiTominaga 

issueありがとうございます。修正しましたのでご確認ください。
