### ISSUE TITLE
[wai-aria-1.1] aria-labelledby (property) 

### ISSUE THREAD

**Issue by yinm** [momdo/momdo.github.io#131]
aria-labelとaria-labelledbyの関係が逆になってるかなと思ったのですが、どうでしょうか？

> If the interface is such that it is not possible to have a visible label on the screen, authors SHOULD use aria-label and SHOULD NOT use aria-labelledby. 
インターフェイスが画面上で可視ラベルを持つことが不可能であるような場合、著者はaria-labelledbyを使用すべきであり、aria-labelを使用すべきではない。

→ インターフェイスが画面上で可視ラベルを持つことが不可能であるような場合、著者はaria-labelを使用すべきであり、aria-labelledbyを使用すべきではない。

**Comment by momdo** [comment]
@yinm 
ありがとうございます。ものの見事に逆になっていましたので、修正しました。
