### ISSUE TITLE
html/dom.html#kinds-of-content の画像が 404 になっている

### ISSUE THREAD

**Issue by linuxmetel** [momdo/momdo.github.io#135]
[ここ](https://momdo.github.io/html/dom.html#kinds-of-content)にある図が 404 になっています。おそらく [de9b965](https://github.com/momdo/momdo.github.io/commit/de9b965a0de71e6a264100a3720b092b928927a3) で入ったもので、埋め込まれた画像のパスは `/images/content-venn.svg` になっていますが、実際は `/html5/images/content-venn.svg` や `/html51/images/content-venn.svg` にしか無いので 404 になっているのだと思います。

latest commit の該当する行: [html/dom.html#L805](https://github.com/momdo/momdo.github.io/blob/7bf9db0aa6e36c2283e51105ec546ee0864046e2/html/dom.html#L805)

**Comment by linuxmetel** [comment]
[WHATWG のサイトの svg ファイル](https://html.spec.whatwg.org/images/content-venn.svg) を持ってきて、 (翻訳するのであれば) 翻訳すれば良さそうですかね、 content-venn.png もありますが、これは svg ファイルの方に 301 でリダイレクトしているようにみえます。

**Comment by momdo** [comment]
@linuxmetel 
ありがとうございます。修正しました。

https://momdo.github.io/html/dom.html#kinds-of-content

/dom.html
https://github.com/momdo/momdo.github.io/commit/0edf978ccee639d9740ff63c2b624df1af75ef03#diff-5bf49306e044da5e960b617e41480163f8dac558a9bc642d4cea0de1a9fb66f7
