### ISSUE TITLE
[html] 4.10.5.3.6 pattern属性の訳調整（multiple属性が併設されている場合の表現）

### ISSUE THREAD

**Issue by SaekiTominaga** [momdo/momdo.github.io#137]
[4.10.5.3.6 pattern属性](https://momdo.github.io/html/input.html#the-pattern-attribute)の一段落目ですが、[原文](https://html.spec.whatwg.org/multipage/input.html#the-pattern-attribute)に照らし合わせると「すなわち」の表現は「または」などに置き換えた方が良いと思います。

原文

> The pattern attribute specifies a regular expression against which the control's [value](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-value), or, when the [multiple](https://html.spec.whatwg.org/multipage/input.html#attr-input-multiple) attribute [applies](https://html.spec.whatwg.org/multipage/input.html#concept-input-apply) and is set, the control's [values](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-values), are to be checked.

提案1: 直訳に近い修正案

```diff
- pattern属性は、コントロールの値すなわち、multiple属性が適用されて設定される場合、コントロールの値がチェックされる対象となる正規表現を指定する。
+ pattern属性は、コントロールの値、またはmultiple属性が適用されて設定される場合はコントロールのそれぞれの値がチェックされる対象となる正規表現を指定する。
```

提案2: 日本語としての分かりやすさを優先した修正案（原文からは離れてしまう）

```diff
- pattern属性は、コントロールの値すなわち、multiple属性が適用されて設定される場合、コントロールの値がチェックされる対象となる正規表現を指定する。
+ pattern属性は、コントロールの値（multiple属性が適用されて設定される場合はそのそれぞれの値）がチェックされる対象となる正規表現を指定する。
```

通常の「control's value」に対して、multiple属性がある場合の「control's values」を日本語でどう表現するのか難しいですね……。
上記は「それぞれの値」としてみましたが、他に良い案があれば!

**Comment by momdo** [comment]
@SaekiTominaga 

コメントありがとうございます（反応遅くなりました）。いただいた案を参考に、下記としてみました。

pattern属性は、チェックされるコントロールの値、または、multiple属性が適用されて設定される場合はコントロールのそれぞれの値に対する正規表現を指定する。

diff：https://github.com/momdo/momdo.github.io/commit/3508bc51a28de2bc75cf1e2a7a93e0d3c129e076#diff-d654750e2009b8241e4b7558a86e120b993a64273c9060b39baf5c5731768e7aR1686

**Comment by SaekiTominaga** [comment]
ご対応ありがとうございます。
変更確認しましたので close します。
