### ISSUE TITLE
属性値構文の説明において属性値ではなく属性名が主語となっている

### ISSUE THREAD

**Issue by skystar0227** [momdo/momdo.github.io#138]
属性値構文の各説明の文章構造は「…属性名は、…任意のリテラルに…を含んではならず、…」となっています。
しかしながらこの説明は属性値に対するものであると考えられるため、主語は属性名ではなく属性値ではないでしょうか。

例として「引用符で囲まれない属性値構文」を次に示しますが、「単一引用符属性値構文」および「二重引用符属性値の構文」も同様です。

翻訳: <https://momdo.github.io/html/syntax.html#unquoted>
> 0個以上の[ASCII空白文字](https://triple-underscore.github.io/infra-ja.html#ascii-whitespace)が続き、1つのU+003D EQUALS SIGN文字が続き、0個以上の[ASCII空白文字](https://triple-underscore.github.io/infra-ja.html#ascii-whitespace)が続き、属性値に対する上記の要件に加えて[属性値](https://momdo.github.io/html/syntax.html#syntax-attribute-value)が続く[属性名](https://momdo.github.io/html/syntax.html#syntax-attribute-name)は、任意のリテラルに[ASCII空白文字](https://triple-underscore.github.io/infra-ja.html#ascii-whitespace) U+0022 QUOTATION MARK文字（"）、 U+0027 APOSTROPHE文字（'）、U+003D EQUALS SIGN文字（=）、U+003C LESS-THAN SIGN文字（<）、U+003E GREATER-THAN SIGN文字（>）、またはU+0060 GRAVE ACCENT文字（`）文字を含んではならず、かつ空文字列であってはならない。

原文を確認すると "The attribute name, followed by …, followed by attribute value, which, in addition to …, must not contain …" という表現なので、 "must not contain …" の主語は "which" ひいては "attribute value" であると考えられます。
直訳すると「属性名、続いて …、続いて …、続いて、…に加えて…を含んではならず、… である属性値。」のような文章でしょうか。

原文: https://html.spec.whatwg.org/#unquoted
> The [attribute name](https://html.spec.whatwg.org/#syntax-attribute-name), followed by zero or more [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace), followed by a single U+003D EQUALS SIGN character, followed by zero or more [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace), followed by the [attribute value](https://html.spec.whatwg.org/#syntax-attribute-value), which, in addition to the requirements given above for attribute values, must not contain any literal [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace), any U+0022 QUOTATION MARK characters ("), U+0027 APOSTROPHE characters ('), U+003D EQUALS SIGN characters (=), U+003C LESS-THAN SIGN characters (<), U+003E GREATER-THAN SIGN characters (>), or U+0060 GRAVE ACCENT characters (`), and must not be the empty string.

翻訳に使用されたときの原文と現在参照している原文は同じものではない可能性もありますが、原文と翻訳とで表している内容が異なるように感じたためイシューを開きました。

**Comment by momdo** [comment]
@skystar0227 

コメントありがとうございます。ご指摘のとおり、主語がおかしかったですね。

コメントに基づいた、文書の枠組みの修正をしました（翻訳として細かい箇所でちょっと怪しいところはありますが）
- diff：https://github.com/momdo/momdo.github.io/commit/2709fea5b8de5b3ef09288ff674902e5d1d192f0#diff-9b41ff9726194117349b52553605b13a8c858b611738ca36e9c2769c3792a543
- 該当箇所：https://momdo.github.io/html/syntax.html#attributes-2

ご確認いただければ幸いです。よろしくお願いいたします。

**Comment by skystar0227** [comment]
@momdo 早速のご対応ありがとうございました。修正を確認して私の理解とよく一致しているように読めましたので本イシューをクローズいたします。

最後になりましたが、素晴らしい翻訳のご提供に感謝しております。
