### ISSUE TITLE
[html]誤訳: stage directions

### ISSUE THREAD

**Issue by hajiifu** [momdo/momdo.github.io#140]
日本語訳をありがとうございます！

戯曲のマークアップについて調べていて誤訳らしきものを見つけたのでご報告致します。

[4.14.3 会話](https://momdo.github.io/html/semantics-other.html#conversations) 中、原文で `stage directions` となっているところが「ステージ方向」と訳されていますが、これはト書きのことだと思います。

技術と関係ない些末な箇所で恐縮ですが、よろしくお願いいたします。

**Comment by momdo** [comment]
@hajiifu 

issue作成ありがとうございます。

下記コミットにて修正しました。
https://github.com/momdo/momdo.github.io/commit/5f578298285fb45309fdbc283739d84f122ef689#diff-e937e22a33d6d544a6ec1c37a09846b36a9b1cf38f6619634fb6daa1b36fabbbR101
