### ISSUE TITLE
[wai-aria-1.2] `aria-details`プロパティ内の本文説明のリンクテキスト誤り

### ISSUE THREAD

**Issue by SaekiTominaga** [momdo/momdo.github.io#141]
- https://www.w3.org/TR/wai-aria-1.2/#aria-details
- https://momdo.github.io/wai-aria-1.2/#aria-details

`aria-details` の本文1行目のリンク「関連する`aria-controls`を参照のこと」は正しくは`aria-describedby`です。

`href` の URL は正しくて、リンクテキストのみ間違っているようです。

**Comment by momdo** [comment]
@SaekiTominaga 
ありがとうございます。修正しました。

https://github.com/momdo/momdo.github.io/commit/65be20715d33c23288fcb60e2c9221f73d490089#diff-0623295a7c97f09907c4dbd4422bebb608a2f1d0c8fa95915867bf17b9d0a05cR11108
