### ISSUE TITLE
HTML5日本語訳 rb要素に誤記

### ISSUE THREAD

**Issue by lostandfound** [momdo/momdo.github.io#15]
お世話になってます。

<http://momdo.github.io/html5/text-level-semantics.html#the-rb-element>

text/htmlにおけるタグ省略の説明

> rb要素が別のrb、rt、rtcまたはrp要素の直前に存在する場合、または親要素に追加のコンテンツが存在しない場合、**rt要素の終了タグは省略してもよい**。

*rb要素の終了タグは省略してもよい* とすべき箇所かと思います。

よろしくお願い致します。

**Comment by momdo** [comment]
コメントありがとうございます。
ご指摘の点、修正しました。
https://github.com/momdo/momdo.github.io/commit/e5e98f990b1f4f410aa65b3ccd6033d45d2c3e9c
