### ISSUE TITLE
semanticsの訳語

### ISSUE THREAD

**Issue by takenspc** [momdo/momdo.github.io#2]
HTML5日本語訳では、semanticsの訳語としてセマンティックが使われていますが、semanticsは名詞でsemanticは形容詞ですので、両者を区別できるように、semanticsの訳語にはセマンティックスかセマンティクスを使ってはいかがでしょう。

semanticsの訳語としてセマンティックが使われている例

- http://www.w3.org/TR/html5/text-level-semantics.html#text-level-semantics
    
    > 4.5 Text-level semantics
- http://momdo.github.io/html5/text-level-semantics.html#text-level-semantics
    
    > 4.5 テキストレベルセマンティック

参考

- http://ejje.weblio.jp/content/semantics
- http://ejje.weblio.jp/content/semantic
- http://www.answers.com/topic/semantics
- http://www.answers.com/topic/semantic

**Comment by momdo** [comment]
原則論としては理解しましたが、semanticsをセマンティクスとすると語感が悪いかなと思うところもありまして、現状はこのように訳出しています。
HTML5仕様書内で単語semanticが出現していたかは定かではないですが、もし出現してないならHTML5で訳し分ける必要というのはないのかもしれません。

いずれにせよ、私も明確な根拠があってこの語を訳出しているわけではないので、少し調べてから結論を出したいと思います。
＃もちろん、semanticsはセマンティ（ッ）クスと訳出しないといけない、という辞書以外の強い根拠があればそれに依りたいと思います。

**Comment by oti** [comment]
原則論というか、「セマンティック」は名詞ではないことは明らかなので、semanticsはセマンティ（ッ）クスと訳されるべきだと思います。辞書が十分な根拠と言えるのではないでしょうか。

> semanticsをセマンティクスとすると語感が悪い

こちらは訳者の主観であると思います。語感についてならば「セマンティックス」か「セマンティクス」かを議論する余地はあると思います:)

**Comment by momdo** [comment]
では、それなりに根拠になりそうな用例を貼っておきます。

コインサスカタカナ語辞典第4版によると、semantic anaysisを「セマンティック-アナリシス」、semantics errorを「セマンティック-エラー」と表記していました。形容詞形と名詞形で明確な区別をしなければならない、というものに対して若干の若干の反論になるのではないでしょうか。

**Comment by oti** [comment]
なるほど……。ありがとうございます。

**Comment by momdo** [comment]
コンサイスカタカナ語辞典の見出し語について、三省堂の辞書問い合わせ窓口（http://dictionary.sanseido-publ.co.jp/support/question.html）から問い合わせてみました。

私信なので全部は書きませんが、
* 英語圏でsemantics errorよりsemantic errorの方が一般的かも
* 日本語のIT用語辞典等で見出し語は、「セマンティ（ッ）クス」とするか「セマンティック」とするかは、ばらつきがあるみたい 

とのことです。

言い換えると、カタカナ語辞典でsemantic errorに「セマンティック-エラー」とするのが妥当か、という先方の返信なので、コンサイスをもってsemanticsの訳語をセマンティックにする、というのは無理筋になってきました。

ただ、IT用語辞典で表記がばらついているとのことなので、一度こちらを私の方で確認して見たいと思います。

**Comment by momdo** [comment]
参考までに少しIT用語辞典を調べてみましたところ、

2011-'12年版 [最新] パソコン・IT用語事典
http://www.amazon.co.jp/dp/4774145793

こちらがsemantics errorを「セマンティックエラー」としていました（コンサイスはこれに引っ張られた、のかもしれません）。

**Comment by momdo** [comment]
HTML Living Standard訳で
semantic：セマンティック
semantics：セマンティックス
に修正予定。

**Comment by takenspc** [comment]
> HTML Living Standard訳で
> semantic：セマンティック
> semantics：セマンティックス
> に修正予定。

ありがとうございます。

**Comment by momdo** [comment]
一応、HTML Living Standardは変更しましたけど、これWAI-ARIAも追随しないと変ですよね……

**Comment by momdo** [comment]
訳し分けると決めた後で、セマンティックスかセマンティクスかで迷っている人がいると聞いて。

**Comment by momdo** [comment]
NVDAに読み上げさせたところ前者に近い気がしたので前者にしておく。

**Comment by momdo** [comment]
HTML5.x訳を除いて、セマンティックスで訳出するようにしているので一応反映されているはず。
