### ISSUE TITLE
HTML5日本語訳 main要素に関する表記

### ISSUE THREAD

**Issue by uchien** [momdo/momdo.github.io#42]
初めまして、W3C仕様日本語訳、とても貴重な資料でいつもお世話になっております。

http://momdo.github.io/html5/grouping-content.html#the-main-element

main要素の説明

> この要素を使用できるコンテキスト：
> フローコンテンツが期待される場所、 **ただしarticle、aside、footer、headerまたはnav要素の祖先を除く。**

の下の行なのですが、 *ただしarticle、aside、footer、headerまたはnav要素を祖先に持たない(場所)。* 
のようなニュアンスかと思い、ご報告いたします。

よろしくお願いします。

**Comment by momdo** [comment]
@uchien
ご指摘のとおりに修正しました。

**Comment by uchien** [comment]
@momdo ありがとうございます！
