### ISSUE TITLE
nav要素のコンテンツモデル、article要素のカテゴリーの文言

### ISSUE THREAD

**Issue by webcre8** [momdo/momdo.github.io#43]
nav要素はmain要素を子孫に持てない要素ですが、現状のコンテンツモデルの「フローコンテンツ、ただしmain要素の子孫を除く」という訳文ではnav要素が子孫に持てない要素のうちにmain要素自体が含まれないように思えます。（原文：Flow content, but with no main element descendants.）

「フローコンテンツ、ただしmain要素を子孫に持たない」とか、「フローコンテンツ、ただしmain要素が子孫になる場合を除く」などのほうが妥当かと思われます。

また、article要素のカテゴリーにも同じ文がありますが、こちらも同様かと思われます（余談ですが、この記述はnav要素と同様にコンテンツ・モデルの項にあるべきですよね。原文に違和感があります）。

ご検討いただければと思います。

**Comment by momdo** [comment]
>余談ですが、この記述はnav要素と同様にコンテンツ・モデルの項にあるべきですよね。原文に違和感があります。

単なるerrataでは。

http://www.w3.org/TR/2015/WD-html51-20151008/semantics.html#the-article-element
https://html.spec.whatwg.org/multipage/semantics.html#the-article-element

**Comment by momdo** [comment]
案：
フローコンテンツ、ただしmain要素を子孫にもたない
