### ISSUE TITLE
nav要素の説明

### ISSUE THREAD

**Issue by webcre8** [momdo/momdo.github.io#44]
原文：The nav element represents a section of a page that links to other pages or to parts within the page: a section with navigation links.

現行訳：nav要素は、他のページへリンクするページのセクション、またはナビゲーションリンクをもつセクションのようなページ内部の一部を表す。

現行ではこの部分が上記のように訳されていますが、「links to other pages or to parts within the page」は「他のページやページ内のいち部分へのリンク」のような意味ではないかと思われます。現行訳ではナビゲーションの定義が「他のページへのリンク」となってしまい、ページ内リンクをナビゲーションに含むことができないように感じられます。

**Comment by momdo** [comment]
案：
nav要素は、他のページへまたはページ内部で一部へリンクするページのセクション、ナビゲーションリンクをもつセクションを表す。

**Comment by momdo** [comment]
案1改で修正しました。
