### ISSUE TITLE
[css2] 10.3.7 絶対配置される非置換要素の場合 の unless

### ISSUE THREAD

**Issue by momdo** [momdo/momdo.github.io#52]
オリジナル issue
http://yoshiko-pg.github.io/slides/20151215-scripty/#28

> If none of the three is 'auto': If both 'margin-left' and 'margin-right' are 'auto', solve the equation under the extra constraint that the two margins get equal values, unless this would make them negative, in which case when direction of the containing block is 'ltr' ('rtl'), set 'margin-left' ('margin-right') to zero and solve for 'margin-right' ('margin-left').

https://drafts.csswg.org/css2/visudet.html#abs-non-replaced-width
 
 
> この3つが'auto'でない場合：'margin-left'および'margin-right'の両方が'auto'である場合、2つのマージンが等しい値を得る追加条件の下で式を解き、等式がその3つを負にする場合を除いて、包含ボックスの方向が'ltr'（'rtl'）の場合、'margin-left'（'margin-right'）を0に設定し'margin-right'（'margin-left'）を解く。

http://momdo.github.io/css2/visudet.html#abs-non-replaced-width

> unless this would make them negative,

の解釈が変なのでは。

1. 等式がその2つのマージンを負にする場合を除いて、
1. 追加条件が2つのマージンを負にする場合を除いて、

後者が妥当な訳出か。

https://www.w3.org/TR/css3-box/#abs-non-replaced-width

> Should we remove the phrase starting with “unless”?

が依然として有効なのか確かめる。

検証サンプルコード。
https://jsfiddle.net/r1rxg4w5/4/

**Comment by momdo** [comment]
どうにもしっくりこないので、@matoriさんに問い合わせてみたところ素晴らしい回答を頂いた（多謝）。これを踏まえて訳をもう一度直してみる：


> If none of the three is 'auto': If both 'margin-left' and 'margin-right' are 'auto', solve the equation under the extra constraint that the two margins get equal values, unless this would make them negative, in which case when direction of the containing block is 'ltr' ('rtl'), set 'margin-left' ('margin-right') to zero and solve for 'margin-right' ('margin-left').

https://drafts.csswg.org/css2/visudet.html#abs-non-replaced-width
 
 
 この3つが'auto'でない場合：'margin-left'と'margin-right'の両方が'auto'である場合、2つのマージンが等しい値を得る追加制約の下で式を解く。ただしこの追加制約が2つのマージンを負にする場合を除く。そして2つのマージンが負になる場合に、包含ボックスの方向が'ltr'（'rtl'）であるならば、'margin-left'（'margin-right'）を0に設定し、'margin-right'（'margin-left'）を解決する。

とするのが妥当な訳ではないか、という結論に。

**Comment by matori** [comment]
あとからもうちょっと考えてみたんですが、

> unless this would make them negative, in which case

はなくても意味は通じますね。
個人的にはあったほうがいいと思いますが。

**Comment by momdo** [comment]
@yoshiko-pg さんに確認したところ、unlessがある状態で問題なさそうということでおしまい。
