### ISSUE TITLE
ARIA Techniques for WCAG 2.0訳をWAICサイトに移管してもらいたい

### ISSUE THREAD

**Issue by momdo** [momdo/momdo.github.io#7]
http://momdo.github.io/WCAG20-TECHS_aria.html について、現状のWAIC『WCAG 2.0 実装方法集』には一切翻訳が記載されていないので、補完目的で訳出した。
今年度にはJISX8341-3:2010の改定が必ず行われる（継続にせよ。JISは5年ごとに必ず見直される）ので、それにあわせて実装方法集も更新されるだろう（という目論見）。
Twitter上で木達さんにメンションを投げたことはあっても（必要であれば当時のツイートを発掘する）、WAICにメールをしたことは無いので、
メールにて、公式に翻訳をWAICに受け取ってもらうにはどうすればよいか（そもそもそういうことをしてくれるのか）を問い合わせてみる。

**Comment by kazuhito-kidachi** [comment]
実装方法集とJISの更新はリンクしません。が、それはそれとして、公式翻訳とし取り扱う件については基本前向きに検討させていただきたく、ぜひWAICまでご連絡ください。

**Comment by kazuhito-kidachi** [comment]
あ、メールありがとうございます（謎

**Comment by momdo** [comment]
レスありがとうございます。
木達さんと内々に話を進めてもWAICの方が困ってしまうと思うので、今し方メールを飛ばしました。
お互い、できること・できないことあると思いますので、そのあたりの詰めは相談させていただくとして、WAIC側で困らない方法で話を進めていただければと。

**Comment by momdo** [comment]
WAICを代表して植木さんとメールのやりとりを数往復させていただいた。
基本的にはWAICに当該訳を受け取っていただける運びになった。
（WAIC側のポリシーに従って、WAICで加工される可能性についても了承した。）

来月中旬にWAIC会合が行われるとのことなので、具体的に動くのはそれ以降。
WCAG20-TECHSの更新は最短で年末を目途に公開する目標とのこと（その時点でのWCAG20-TECHS最新版にあわせる）。

**Comment by momdo** [comment]
#8 の件でWAICにご相談させて頂く折に、窓口を実務担当のWAIC WG2伊敷さん

**Comment by momdo** [comment]
6/3にWAICの翻訳に関する作業部会が設置されることが発表された。

WCAG関連文書の翻訳に関する臨時作業部会の設置および委員の募集 | 新着情報 | ウェブアクセシビリティ基盤委員会（WAIC） 
http://waic.jp/news/20160603.html

どうマージするかはこの部会で決定されるはず。

**Comment by momdo** [comment]
WAIC翻訳WGにリモート参戦した。
とりあえず https://github.com/waic/wcag20/tree/translation_wcag_documents が作業ブランチとなる模様。ファイルはXML。
まだWAIC側の受入体勢が整い切れてないので、体勢が完了し次第、プルリクを行う。

**Comment by momdo** [comment]
https://twitter.com/waic_jp/status/855005873600516097
WAICでの翻訳が公開された。
