### ISSUE TITLE
[css2]ページタイトルを日本語に統一

### ISSUE THREAD

**Issue by maiha2** [momdo/momdo.github.io#72]
> title要素は翻訳メモリーのas-isなので、日本語になってるのもあれば、なってないのもある

の事情でページタイトルの日本語・英語が統一されていないため、統一させたい🍌

**Comment by momdo** [comment]
@maiha2 
英語と日本語、どっちに統一させたいですか？

**Comment by maiha2** [comment]
日本語訳のページですし、日本語でいいかなと思うのですが…(｡ŏ﹏ŏ)

**Comment by momdo** [comment]
@maiha2 
これで日本語に統一できてると思うので、確認くださいな。

**Comment by momdo** [comment]
memo
via https://twitter.com/kecy_/status/742695961508483072

**Comment by momdo** [comment]
統一できてるので閉じておきます。
