### ISSUE TITLE
[css2] 15.2節 「次で一致され」

### ISSUE THREAD

**Issue by momdo** [momdo/momdo.github.io#77]
https://momdo.github.io/css2/fonts.html#algorithm

https://twitter.com/GeckoTang/status/752826471954075648

>'font-weight' is matched next, 

> 'font-weight'は次で一致され、

これが疑問という指摘。

**Comment by geckotang** [comment]
@momdo 

- 'font-weight'は次に一致され、
- 次に'font-weight'が一致され、

とかかなぁ〜？と考えていました。
