### ISSUE TITLE
[css2] 15.3.1.1 「セリフ先端」という訳出

### ISSUE THREAD

**Issue by momdo** [momdo/momdo.github.io#78]
https://twitter.com/SaekiTominaga/status/752831604716806144

> または実際に（スラブセリフを含む）セリフ先端を持つ。

セリフ先端という訳出が疑問。

**Comment by oti** [comment]
https://ja.wikipedia.org/wiki/%E3%82%BB%E3%83%AA%E3%83%95_(%E6%96%87%E5%AD%97)
http://www.akibatec.net/wabunfont/study/basic/basic2.html

> or have actual serifed endings (including slab serifs).

「セリフ」というのがそもそも「グリフの起筆部と終筆部にある飾り」のことなので、 `serifed endings` という原文自体が重複的な説明と感じます。

`font-family: serif;` で適用されるべきフォントとして、セリフ体そのものか、それに準じたデザインのフォントであるという説明箇所だと思うので、以下のような変更ではどうでしょうか？

```
-- または実際に（スラブセリフを含む）セリフ先端を持つ。
++ または実際に（スラブセリフを含む）セリフ体である。
```

**Comment by makotom** [comment]
// 書体にとても詳しい訳ではないのであまり偉そうな言い方はできないのですが,
http://www.w3.org/TR/CSS22/fonts.html#serif-def の文脈に鑑みると, もしくは, セリフを持つセリフ体でない書体もあると思うので, "セリフ体である" という文末は違うのかなーなんて思ったりします.

大げさに意訳して "実際にセリフを (先端に) 持つ" とか?

余談だけど, serifed endings を decorated endings とか slightly-projected endings (cf. http://www.oxforddictionaries.com/definition/english/serif ) とかに読み替えたらどれくらいマズいかなあ?

**Comment by momdo** [comment]
一応並べてみます

> Glyphs of serif fonts, as the term is used in CSS, tend to have finishing strokes, flared or tapering ends, or have actual serifed endings (including slab serifs).

http://www.w3.org/TR/CSS22/fonts.html#serif-def
> CSSで使用される用語serif（セリフ）フォントのグリフは、ストローク仕上げ、フレア、または先細り端を持つ傾向にある、または実際に（スラブセリフを含む）セリフ先端を持つ。

https://momdo.github.io/css2/fonts.html#serif-def

なんかコメントあります？ @webcre8
