### ISSUE TITLE
header要素およびfooter要素のコンテンツモデルの表示について

### ISSUE THREAD

**Issue by wildwest-service** [momdo/momdo.github.io#80]
header要素・footer要素のコンテンツモデルに「フローコンテンツ、ただしheader、footer、またはmain要素の子孫を除く。」と書いてあるのを見て、headerとfooterはmainの子孫としてはいけないと誤解している人がいるようです。
（「この要素を使用できるコンテキスト」と記述位置が近いためという理由もありそうですが）

「フローコンテンツ、ただしheader、footer、またはmain要素は子孫として含めない。」とするのはどうでしょうか。

**Comment by momdo** [comment]
https://html.spec.whatwg.org/multipage/semantics.html#the-header-element
https://momdo.github.io/html/semantics.html#the-header-element

**Comment by makotom** [comment]
content model の意味を無視して結果勘違いしちゃう人のことをどれくらい真剣に考える必要があるか, という議論は別に置いておくとして, 原文に忠実な訳を目指すとすると,
"xxx を子孫として含めない (excluding xxx as descendants)" と "子孫 xxx を持たない (without xxx descendants)" は訳し分けるべきかと思います. (まあこちらも, 英文側で厳密に使い分けられているかという議論はありそうですが.)

ただ, "除く" という述語が浮いている (i.e. 誤解を生みやすい), という意見も正しいと思います.

ここは, "ただし header, footer または main 要素の子孫を持たない" くらいがよいのではないでしょうか?

**Comment by momdo** [comment]
@wildwest-service @makotom 
コメントありがとうございました。
