### ISSUE TITLE
[css2] 2.1　終盤の「しかし、最後の宣言はセミコロンがついてもよい。」

### ISSUE THREAD

**Issue by momdo** [momdo/momdo.github.io#83]
https://twitter.com/Windy_roa_d/status/788344412363304961 いわく：

> 2.1章終盤の「しかし、最後の宣言はセミコロンがついてもよい。」は「つかなくてもよい」かな…？ #tokyocssspecs

原文：
> The first thing to notice is that several declarations are grouped within a block enclosed by curly braces ({...}), and separated by semicolons, though the last declaration may also be followed by a semicolon.

現行訳：
> 最初に気づくことは、複数の宣言が波括弧で囲まれたブロック内でグループ化され（{...}）、セミコロンで区切られていることだろう。しかし、最後の宣言はセミコロンがついてもよい。

https://momdo.github.io/css2/intro.html#html-tutorial
やや微妙な気がするので、後で見直す。

**Comment by makotom** [comment]
分解すると "declarations are ... separated by semicolons, though ... may ... be followed by a semicolon" なので, 正確な訳としては "セミコロンで区切られ" "(最後に) セミコロンがついてもよい" であると考えらえる.
要するに, declarations.split(";") の結果の最後が空でも構わない, ということなので.

あとは日本語表現のわかりやすさの問題かと......

**Comment by momdo** [comment]
改良試訳：
最初に気づくことは、複数の宣言が波括弧で囲まれたブロック内でグループ化され（{...}）、セミコロンで区切られている（とはいえ、最後の宣言は同様にセミコロンがあってもよい）ことだろう。

ちょっと英語に引っ張られすぎかなぁ…。

**Comment by makotom** [comment]
最後の宣言 "の後にも"
かな.

原文も also が何とどう also なのか不明なだけに, 訳文も "同様に" が浮きますね......

**Comment by momdo** [comment]
あー、後にもとしないとおかしいですね…。

最初に気づくことは、複数の宣言が波括弧で囲まれたブロック内でグループ化され（{...}）、セミコロンで区切られている（*とはいえ、最後の宣言の後にもセミコロンがあってもよい*）ことだろう。

こんなところですか。

**Comment by oti** [comment]
> 最初に気づくことは、複数の宣言が波括弧で囲まれたブロック内でグループ化され（{...}）、セミコロンで区切られている（とはいえ、_最後の宣言の後にも_セミコロンがあってもよい）ことだろう。

LGTM!

CSS著者的には、宣言をセミコロンで閉じるのは当たり前で、でも「閉じる」んではなくて「宣言と宣言を区切ってる」ていうのが仕様側の本質で、そこの前提認識の差が訳に違和感を与えてるのかなーと感じてました。

「セミコロンで区切ってる→_区切りだから最後はいらない_→とはいえ最後にあってもいい」が仕様側の説明なんですけど、もし意訳を挟む余地があるなら `とはいえ` 部分を `そして` に置き換えると個人的にはすんなり読める文章になるかなと思いました。

> 最初に気づくことは、複数の宣言が波括弧で囲まれたブロック内でグループ化され（{...}）、セミコロンで区切られている（_そして_、最後の宣言の後にもセミコロンがあってもよい）ことだろう。

*とはいえ*、セミコロンをclosingではなくdelimiterだと最初からわかっている人にとっては逆に違和感のある日本語になってしまうし、 `though ~ may be ~ (may be through ?)` の文法からはかなり離れた和訳になっちゃうなとも思っています。強く主張する気はないので、

> とはいえ、_最後の宣言の後にも_セミコロンがあってもよい

こちらの訳に一票で。

**Comment by momdo** [comment]
@oti

逆接がなんとなく違和感があるのは、

>最初に気づくことは、複数の宣言が波括弧で囲まれたブロック内でグループ化され（{...}）、セミコロンで区切られている（とはいえ、最後の宣言の後にもセミコロンが***なく***てもよい）ことだろう。

と本来的にはなるはずだ、と言うことなんですよね結局は。

@makotom
これ肯定文を否定文にしちゃっていいもんなんですかね…

**Comment by makotom** [comment]
英語の文章 (... are separated by) の印象としては
hoge | piyo | fuga
であって
hoge | piyo | fuga |
ではないと考えるので, 否定文とすると厳密性に欠けると思います.

> とはいえ, (区切り子である) セミコロンは最後の宣言の後にもあってもよい

などと, 文節の順序を入れ替え, 区切り子の取り扱いについて議論していることを明示する, といった方法でどうにかできないものでしょうか......

**Comment by momdo** [comment]
困ったときは辞書に戻ろう…


> though  1b [追加的に従節を導いて] もっとも…であるが.
http://ejje.weblio.jp/content/though


> とはいえ→とはいうものの ［接］前に述べた事柄と相反する内容を導く語。そうはいっても。とはいえ。「―、やはりこわい」
http://dictionary.goo.ne.jp/jn/159822/meaning/m0u/
http://dictionary.goo.ne.jp/jn/159821/meaning/m0u/


> もっとも ［接］前の事柄を肯定しつつ、例外あるいは一部相反する内容を補足するときに用いる。とはいうものの。なるほどそうだが。ただし。
http://dictionary.goo.ne.jp/jn/219472/meaning/m0u/


まことさん提案のように、但し書きを後ろに回した方が良さそうですね。

>最初に気づくことは、複数の宣言が波括弧で囲まれたブロック内でグループ化され（{...}）、セミコロンで区切られていることだろう。もっとも、セミコロンが最後の宣言の後にもあってもよい。

これで行きます。
