### ISSUE TITLE
[css2] HTML属性値内の引用符がエスケープされていない

### ISSUE THREAD

**Issue by kwkbtr** [momdo/momdo.github.io#84]
以下の部分で、`title`属性の属性値内の引用符`"`がエスケープされておらず、不正な指定になっています。
https://github.com/momdo/momdo.github.io/blob/a6fd8d5784fb1c2546016ca76a7dfaef294f8d74/css2/indexlist.html#L84
英語版では`&quot;`になっています。
https://github.com/w3c/csswg-drafts/blob/62b8efe19a7923726ccbc436e8e1024285e265ec/css2/indexlist.html#L87

**Comment by momdo** [comment]
見事に`""@charset""`になってますね…

（言い訳をすると、翻訳に使っているOmegaTのHTMLパーサーが古いためこうなってしまうんですよね…）
