### ISSUE TITLE
[html] 2.3.5.6 タイムゾーンの訳出

### ISSUE THREAD

**Issue by momdo** [momdo/momdo.github.io#99]
https://twitter.com/robert_KIMATA/status/954337077528641536

> "if the time-zone offset is not zero" が掛かっているのは "a U+002D HYPHEN-MINUS character (-)" だけで +00:00 は有りかと思うのですが、もんどさん訳だと +-両方に掛かっているように読めます。

これについて検討する。

**Comment by makotom** [comment]
FYI.
https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

**Comment by momdo** [comment]
原文
Either a U+002B PLUS SIGN character (+) or, if the time-zone offset is not zero, a U+002D HYPHEN-MINUS character (-), representing the sign of the time-zone offset
改訳案
タイムゾーンオフセットの符号を表す、U+002B PLUS SIGN文字（+）、またはタイムゾーンオフセットが0でない場合のU+002D HYPHEN-MINUS文字（-）のいずれか
